version: '3.1'

services:
    mongodb:
        hostname: mongodb
        image: mongo:4.4.1
        networks:
            - service-swarm
        ports:
            - 27017:27017
        volumes: 
            -   mongodb_data:/data/db
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager]

volumes: 
    mongodb_data:
        name: swarm_mongodb_data
secrets:
    db_password:
        external: true

networks: 
    service-swarm: